# Beat The Bookies: Predicting EPL Matches
_Team C_

__Mohammad Ali Syed, Abdul Al-Fahim, Dylan Hoi, Henry Chen, Chris Wong & Yolanne Lee__

**Contents:**

[Section 1](#section1): Introduction

[Section 2](#section2): Data Import

[Section 3](#section3): Data Transformation & Exploration

[Section 4](#section4): Methodology Overview

[Section 5](#section5): Model Training & Validation

[Section 6](#section6): Results

[Section 7](#section7): Final Predictions on Test Set

## Introduction
<a name='section1'></a>

## Data Import
<a name='section2'></a>

In [1]:
#Import packages
import numpy as np
import pandas as pd
import datetime as datetime

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, classification_report,confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

#For Visualisation
from sklearn.tree import export_graphviz
from subprocess import call
from IPython.display import Image

import matplotlib.pyplot as plt


In [2]:
#Load data

#Change this to your directory
dirName = 'Data_Files/'
filePath = dirName + 'epl-training.csv'

data = pd.read_csv(filePath)
#Remove empty nan columns at the end
data = data.iloc[:, 0:22]
pd.set_option('display.max_columns', None)
data.head()

Date       HomeTeam   AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
0  16/08/08        Arsenal  West Brom     1     0   H     1     0   H   
1  16/08/08         Bolton      Stoke     3     1   H     3     0   H   
2  16/08/08        Everton  Blackburn     2     3   A     1     1   D   
3  16/08/08           Hull     Fulham     2     1   H     1     1   D   
4  16/08/08  Middlesbrough  Tottenham     2     1   H     0     0   D   

      Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  
0      H Webb  24   5   14    4  11   8   7   5   0   0   0   0  
1       C Foy  14   8    8    2  13  12   4   3   1   2   0   0  
2  A Marriner  10  15    5   11  11   9   3   5   2   2   0   0  
3    P Walton  11  12    6    6  10   9   5   6   3   0   0   0  
4  M Atkinson  14   8   10    5  11  12   7   9   1   2   0   0

## Data Transformation & Exploration
<a name='section3'></a>

In [3]:
#Helper Functions

def corr_matrix(X, feature):
    corr= X.corr()
    corr_y = abs(corr[feature])
    highest_corr = corr_y[corr_y >0.2]
    highest_corr.sort_values(ascending=True)
    return highest_corr

def rf_model(X_train, X_test, y_train, y_test):
    rf=RandomForestClassifier(random_state = 42)
    rf.fit(X_train, y_train)
    preds = rf.predict(X_test)
    accuracy = calc_accuracy(preds, y_test)
    return rf, preds, accuracy

def feat_importances(X_train, rf):
    feature_importances = list(zip(X_train, rf.feature_importances_))
    feature_importances_ranked = sorted(feature_importances, key = lambda x: x[1], reverse = True)
    return feature_importances_ranked

def select_feat(X_train, y_train):
    feature_selector = SelectFromModel(RandomForestClassifier(random_state = 42)).fit(X_train, y_train)
    selected_feat= X_train.columns[(feature_selector.get_support())]
    return selected_feat

def calc_accuracy(preds, labels):
    accuracy = accuracy_score(labels, preds) * 100
    return accuracy

In [4]:
############################################# Feature Visualisation
# Visualise correlations between different statistics
from pandas.plotting import scatter_matrix

# Sort data by teams
teams = {}
referees = {}
for i in data.groupby('HomeTeam').mean().T.columns:
    teams[i] = []
for i in data.groupby('Referee').mean().T.columns:
    referees[i] = []

# Team Summary Statistics
home_team_stats = pd.DataFrame()
away_team_stats = pd.DataFrame()

teams = pd.unique(data[["HomeTeam"]].values.ravel())

for team in teams:
    # Compute summary stats as home team
    team_stats = data[(data["HomeTeam"] == team)]
    team_stats = team_stats.iloc[:, [3, 6, 10, 12, 14, 16, 18, 20]]
    team_stats = team_stats.sum()

    performance = data[(data["HomeTeam"] == team)].iloc[:, 5]
    num_vals = len(performance)
    
    performance = performance.value_counts()
    performance_keys = performance.keys()
    performance_values = performance.values
    performance = zip(performance.keys(), performance.values)
    
    for key, value in performance:
        metric = value/num_vals
        
        if key == "H":
            team_stats["Win Rate"] = metric
            
        elif key == "A":
            team_stats["Lose Rate"] = metric
        
        else:
            team_stats["Draw Rate"] = metric

    home_team_stats[team] = pd.DataFrame(team_stats)

    # Compute summary stats as away team
    team_stats = data[(data["AwayTeam"] == team)]
    team_stats = team_stats.iloc[:, [4, 7, 11, 13, 15, 17, 19, 21]]
    team_stats = team_stats.sum()

    performance = data[(data["AwayTeam"] == team)].iloc[:, 5]
    num_vals = len(performance)

    performance = performance.value_counts()
    performance_keys = performance.keys()
    performance_values = performance.values
    performance = zip(performance.keys(), performance.values)
    
    for key, value in performance:
        metric = value/num_vals
        
        if key == "A":
            team_stats["Win Rate"] = metric
            
        elif key == "H":
            team_stats["Lose Rate"] = metric
        
        else:
            team_stats["Draw Rate"] = metric


    away_team_stats[team] = pd.DataFrame(team_stats)

# Sort by strongest to weakest team, by win rate
home_team_stats = home_team_stats.sort_values(by='Win Rate', axis=1, ascending=False)
away_team_stats = away_team_stats.sort_values(by='Win Rate', axis=1, ascending=False)
home_team_stats
#Interesting to note, Man U ranked lower on every metric except fouls and yellow cards compared to Chelsea but had higher win rate -> could suggest the more aggressive the team, the higher the win rate
# print(home_team_stats.iloc[:, 0])
# print(away_team_stats.iloc[:, 0])
# print(np.array(home_team_stats.iloc[:, 0]) - np.array(away_team_stats.iloc[:, 0]))

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

In [5]:
#Correlation matrix between full time goals and other features
highest_corr = corr_matrix(data, "FTHG")
print("FTHG: \n" + str(highest_corr))

highest_corr = corr_matrix(data, "FTAG")
print("FTAG: \n" + str(highest_corr))

FTHG: 
FTHG    1.000000
HTHG    0.686279
HS      0.291868
HST     0.447116
Name: FTHG, dtype: float64
FTAG: 
FTAG    1.000000
HTAG    0.689755
AS      0.329803
AST     0.455887
Name: FTAG, dtype: float64


In [6]:
#Split dataset into input and output data

#Output variable
y = data.iloc[:, 5:6]
print(y)
#Reformat y to make it suitable for LabelEncoder
y = np.array(y).reshape(len(y))
#Encode y
y = LabelEncoder().fit_transform(y)
#Input variables
#Remove give away columns such as goals scored
data_filtered = data.drop(labels = data.columns[[3, 4, 5, 6, 7, 8]], axis = 1)

     FTR
0      H
1      H
2      A
3      H
4      H
...   ..
4935   H
4936   H
4937   H
4938   H
4939   A

[4940 rows x 1 columns]


In [7]:
#Data preprocessing

#Dates
data_filtered['Date'] = pd.to_datetime(data_filtered['Date'])
#year has been removed as we need to predict future results -> https://towardsdatascience.com/machine-learning-with-datetime-feature-engineering-predicting-healthcare-appointment-no-shows-5e4ca3a85f96
data_filtered['Month'] = data_filtered['Date'].dt.month
data_filtered['Week'] = data_filtered['Date'].dt.isocalendar().week
data_filtered['Day'] = data_filtered['Date'].dt.day
#Extract encoded dates
dates_split = data_filtered.iloc[:, 16:19]
#Remove encoded dates and original date column
data_filtered = data_filtered.drop(labels = data_filtered.columns[[0, 16, 17, 18]], axis = 1)

#Encode categorical data
encoder = OneHotEncoder(handle_unknown='ignore')

#Teams
home_t = data_filtered.iloc[:, 0:1]
home_t = encoder.fit_transform(home_t)

away_t = data_filtered.iloc[:, 1:2]
away_t = encoder.fit_transform(away_t)
data_filtered = data_filtered.drop(labels = data_filtered.columns[[0,1]], axis = 1)

#Referees 
ref = data_filtered.iloc[:, 0:1]
ref = encoder.fit_transform(ref)
data_filtered = data_filtered.drop(labels = data_filtered.columns[[0]], axis = 1)

#Re-stack columns
data_filtered = data_filtered.join(pd.DataFrame(ref.toarray()), rsuffix = '_ref')
data_filtered = data_filtered.join(pd.DataFrame(home_t.toarray()), rsuffix = '_home')
data_filtered = data_filtered.join(pd.DataFrame(away_t.toarray()), rsuffix = '_away')
data_filtered = dates_split.join(data_filtered)
data_filtered.columns = data_filtered.columns.astype(str)
data_filtered.head()

Month  Week  Day  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR    0  \
0      8    33   16  24   5   14    4  11   8   7   5   0   0   0   0  0.0   
1      8    33   16  14   8    8    2  13  12   4   3   1   2   0   0  0.0   
2      8    33   16  10  15    5   11  11   9   3   5   2   2   0   0  0.0   
3      8    33   16  11  12    6    6  10   9   5   6   3   0   0   0  0.0   
4      8    33   16  14   8   10    5  11  12   7   9   1   2   0   0  0.0   

     1    2    3    4    5    6    7    8    9   10   11   12   13   14   15  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    16   17   18   19   20   21   22   23   24   25   26   27   28   29   30  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    31   32   33   34   35   36   37   38   39   40   41   42  0_home  1_home  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0     0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0     0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0     0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0     0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0     0.0   

   2_home  3_home  4_home  5_home  6_home  7_home  8_home  9_home  10_home  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0      0.0   
1     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0      0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0      0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0      0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0      0.0   

   11_home  12_home  13_home  14_home  15_home  16_home  17_home  18_home  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      1.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      1.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   19_home  20_home  21_home  22_home  23_home  24_home  25_home  26_home  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      1.0      0.0      0.0      0.0      0.0      0.0   

   27_home  28_home  29_home  30_home  31_home  32_home  33_home  34_home  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   35_home  36_home  37_home    0    1    2    3    4    5    6    7    8  \
0      0.0      0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.0      0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [16]:
#Train model on entire featureset
X_train, X_test, y_train, y_test = train_test_split(data_filtered, y, test_size=0.3, random_state=42)
rf, preds, base_accuracy = rf_model(X_train, X_test, y_train, y_test)
print("Accuracy on entire featureset: " + str(base_accuracy) + "%")


Accuracy on entire featureset: 56.14035087719298%


In [ ]:
#Print rf tree N.B. may not work without importing graphviz, random forest images will be on GitHub
tree = rf.estimators_[10]  #Take 10th random tree
export_graphviz(tree, out_file='featuresetTree.dot', feature_names = list(data_filtered.columns),
                rounded = True, proportion = False, 
                precision = 2, filled = True)
call(['dot', '-Tpng', 'featuresetTree.dot', '-o', 'featuresetTree.png'],shell=True)

In [14]:
#Train model without Referee feature
data_filtered_no_ref = data_filtered.iloc[:, 0:15].join(data_filtered.iloc[:, 58:])
X_train, X_test, y_train, y_test = train_test_split(data_filtered_no_ref, y, test_size=0.3, random_state=42)
rf, preds, accuracy = rf_model(X_train, X_test, y_train, y_test)
print("Accuracy without Referee: " + str(accuracy) + "%")
print("Difference from before: " + str(accuracy - base_accuracy) + "%")
#Ref is having negative impact so remove
data_filtered = data_filtered_no_ref

Accuracy without Referee: 56.14035087719298%
Difference from before: -1.6869095816464252%


0

In [ ]:
#Print rf tree (no ref)
tree = rf.estimators_[10]  #Take 10th random tree
export_graphviz(tree, out_file='featuresetTreeNoRef.dot', feature_names = list(data_filtered.columns),
                rounded = True, proportion = False, 
                precision = 2, filled = True)
call(['dot', '-Tpng', 'featuresetTreeNoRef.dot', '-o', 'featuresetTreeNoRef.png'],shell=True)

In [15]:
#Train model without Date feature
data_filtered_no_date = data_filtered.iloc[:, 3:]
X_train, X_test, y_train, y_test = train_test_split(data_filtered_no_date, y, test_size=0.3, random_state=42)
rf, preds, accuracy = rf_model(X_train, X_test, y_train, y_test)
print("Accuracy without Dates: " + str(accuracy) + "%")
print("Difference from before: " + str(accuracy - base_accuracy) + "%")

Accuracy without Dates: 56.00539811066126%
Difference from before: -1.8218623481781435%


In [ ]:
#Print rf tree (no dates)
tree = rf.estimators_[10]  #Take 10th random tree
export_graphviz(tree, out_file='featuresetTreeNoDates.dot', feature_names = list(data_filtered_no_date.columns),
                rounded = True, proportion = False, 
                precision = 2, filled = True)
call(['dot', '-Tpng', 'featuresetTreeNoDates.dot', '-o', 'featuresetTreeNoDates.png'],shell=True)

In [53]:
#Train model on only in-game stats to identify most important ones
data_filtered_only_game_stats = data_filtered.iloc[:, 3:15]
X_train, X_test, y_train, y_test = train_test_split(data_filtered_only_game_stats, y, test_size=0.3, random_state=42)
rf, preds, all_stats_accuracy = rf_model(X_train, X_test, y_train, y_test)
print("Accuracy on all in-game stats: " + str(all_stats_accuracy) + "%")

Accuracy on all in-game stats: 55.06072874493927%


In [54]:
#Visualise and analyse initial results

#Display feature importances in descending order
feature_importances = feat_importances(X_train, rf)
print("Feature Importances: ")
[print('Feature: {:35} Importance: {}'.format(*pair)) for pair in feature_importances];

print("\nConfusion Matrix: ")
print(confusion_matrix(y_test, preds))
print("\nClassification Report: ")
print(classification_report(y_test, preds))
#Important note: AF/HF rank higher than HC/AC

Feature Importances: 
Feature: HST                                 Importance: 0.13373568693956137
Feature: AST                                 Importance: 0.11086929727346594
Feature: HS                                  Importance: 0.10711965963253876
Feature: AS                                  Importance: 0.10459574408160308
Feature: AF                                  Importance: 0.10278875719257885
Feature: HF                                  Importance: 0.10274903136845186
Feature: HC                                  Importance: 0.09664473425445547
Feature: AC                                  Importance: 0.09167319027635455
Feature: AY                                  Importance: 0.06454575651360132
Feature: HY                                  Importance: 0.0615627757744895
Feature: AR                                  Importance: 0.012278852078380604
Feature: HR                                  Importance: 0.011436514614518712

Confusion Matrix: 
[[244  46 127]
 [134  50 186]
 [1

In [55]:
#Feature Selection
#change names and display selected features more nicely, ideally with their importance, gini impurity...
selected_feat = select_feat(X_train, y_train)
print(selected_feat)

Index(['HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC'], dtype='object')


In [56]:
#Train model on selected in-game stats only
indexes = []
for feat in selected_feat:
    indexes.append(data_filtered_only_game_stats.columns.get_loc(feat))
    
data_filtered_filtered_game_stats = data_filtered_only_game_stats.iloc[:, indexes]

X_train, X_test, y_train, y_test = train_test_split(data_filtered_filtered_game_stats, y, test_size=0.3, random_state=42)
rf, preds, reduced_stats_accuracy = rf_model(X_train, X_test, y_train, y_test)
print("Accuracy on reduced in-game stats: " + str(reduced_stats_accuracy) + "%")
print("Difference compared to all in-game stats: " + str(reduced_stats_accuracy - all_stats_accuracy) + "%")

print("\nConfusion Matrix: ")
print(confusion_matrix(y_test, preds))
print("\nClassification Report: ")
print(classification_report(y_test, preds))

Accuracy on reduced in-game stats: 54.79082321187584%
Difference compared to all in-game stats: -0.26990553306342946%

Confusion Matrix: 
[[234  39 144]
 [107  64 199]
 [118  63 514]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.51      0.56      0.53       417
           1       0.39      0.17      0.24       370
           2       0.60      0.74      0.66       695

    accuracy                           0.55      1482
   macro avg       0.50      0.49      0.48      1482
weighted avg       0.52      0.55      0.52      1482



In [57]:
#Visualisation of new featureset/tree

In [58]:
#Produce new dataset
#Fix column names
#Restack teams and dates

#Original teams are needed to be able to compute priors
data_new = data.iloc[:, [1, 2]].join(data_filtered_filtered_game_stats)
data_new = dates_split.join(data_new)

#Stack previously removed giveaway columns
data_new = data_new.join(data.iloc[:, [3, 4, 6, 7, 8]])

#Feature engineer second half goals
#Second half home goals
SHHG = np.array(data.iloc[:, [3]]) - np.array(data.iloc[:, [6]])
#Second half away goals
SHAG = np.array(data.iloc[:, [4]]) - np.array(data.iloc[:, [7]])
data_new['SHHG'] = pd.DataFrame(SHHG)
data_new['SHAG'] = pd.DataFrame(SHAG)
data_new.columns = data_new.columns.astype(str)
data_new.head()
#One hot encode dates? -> make the one hot columns but dont stack now, will be better to do after priors all together with teams

Month  Week  Day       HomeTeam   AwayTeam  HS  AS  HST  AST  HF  AF  HC  \
0      8    33   16        Arsenal  West Brom  24   5   14    4  11   8   7   
1      8    33   16         Bolton      Stoke  14   8    8    2  13  12   4   
2      8    33   16        Everton  Blackburn  10  15    5   11  11   9   3   
3      8    33   16           Hull     Fulham  11  12    6    6  10   9   5   
4      8    33   16  Middlesbrough  Tottenham  14   8   10    5  11  12   7   

   AC  FTHG  FTAG  HTHG  HTAG HTR  SHHG  SHAG  
0   5     1     0     1     0   H     0     0  
1   3     3     1     3     0   H     0     1  
2   5     2     3     1     1   D     1     2  
3   6     2     1     1     1   D     1     0  
4   9     2     1     0     0   D     2     1

In [59]:
#See if second half goals have significant correlation to total goals
highest_corr = corr_matrix(data_new, "FTHG")
print("FTHG: \n" + str(highest_corr))

highest_corr = corr_matrix(data_new, "FTAG")
print("FTAG: \n" + str(highest_corr))
#Second half goals do have very strong correlation

FTHG: 
HS      0.291868
HST     0.447116
FTHG    1.000000
HTHG    0.686279
SHHG    0.769173
Name: FTHG, dtype: float64
FTAG: 
AS      0.329803
AST     0.455887
FTAG    1.000000
HTAG    0.689755
SHAG    0.777641
Name: FTAG, dtype: float64


In [60]:
#Computing priors
#Number of previous wins
goal_difference=[]
wins_away=0
wins_home=0
draw=0

#calculating difference in goals 
for j in range(0,len(data_new)):
    goal_difference.append(data_new['FTHG'].iloc[j]-data_new['FTAG'].iloc[j])

#Assign home,away or draw label for each outcome
for i in range(0,len(goal_difference)):
    if goal_difference[i]<0:
        goal_difference[i]='A'
        wins_away=wins_away+1
    elif goal_difference[i]>0:
        goal_difference[i]='H'
        wins_home=wins_home+1
    else:
        goal_difference[i]='D'
        draw=draw+1
        
#create new column and print out values
data_new['Win']=goal_difference
print('Total wins away: ',wins_away)
print('Total wins Home: ',wins_home)
print('Total draws: ',draw)
data_new.head()



Total wins away:  1481
Total wins Home:  2247
Total draws:  1212


Month  Week  Day       HomeTeam   AwayTeam  HS  AS  HST  AST  HF  AF  HC  \
0      8    33   16        Arsenal  West Brom  24   5   14    4  11   8   7   
1      8    33   16         Bolton      Stoke  14   8    8    2  13  12   4   
2      8    33   16        Everton  Blackburn  10  15    5   11  11   9   3   
3      8    33   16           Hull     Fulham  11  12    6    6  10   9   5   
4      8    33   16  Middlesbrough  Tottenham  14   8   10    5  11  12   7   

   AC  FTHG  FTAG  HTHG  HTAG HTR  SHHG  SHAG Win  
0   5     1     0     1     0   H     0     0   H  
1   3     3     1     3     0   H     0     1   H  
2   5     2     3     1     1   D     1     2   A  
3   6     2     1     1     1   D     1     0   H  
4   9     2     1     0     0   D     2     1   H

## Methodology Overview
<a name='section4'></a>

## Model Training & Validation
<a name='section5'></a>

## Results
<a name='section6'></a>

## Final Predictions on Test Set
<a name='section7'></a>